### ISSUE TITLE
extract audio from video

### ISSUE THREAD

**Issue by Hesesses** [pascalbaljetmedia/laravel-ffmpeg#125]
When using ffmpeg on command line I have:
`ffmpeg -i video.mp4 -ss 00:03:05 -t 00:00:45 -vn -acodec copy audio.aac`

I would like to extract audio (copy, not re encoding) from video and specify start (-ss) and duration (-t) timecodes

Is this possible to do this with laravel-ffmpeg?

**Comment by pascalbaljet** [comment]
You could add the -ss and -t filters by using the `addFilter()` method but for this specific request you could also use the `ClipFilter`, but are described in the documentation. The constructor of `ClipFilter` has a second (optional) paramater `$duration`.

To copy the audio stream instead of re-encoding I think you need to create a custom Audio format. I've haven't tested it but I think you need something like this:

```php

use FFMpeg\Format\Audio\DefaultAudio;

class Copy extends DefaultAudio
{
    public function __construct()
    {
        $this->audioCodec = 'copy';
    }

    public function getAvailableAudioCodecs()
    {
        return ['copy'];
    }
}
```
