### ISSUE TITLE
Add multiple filters

### ISSUE THREAD

**Issue by chantrea** [pascalbaljetmedia/laravel-ffmpeg#27]
Hi I want to add multiple filters and you please give me the example how can I add multiple filters
I tried many way
#number1
->addFileter('-preset', 'ultrafast')
->addFilter('-crf', 22)
#number2
->addFileter('-preset', 'ultrafast', '-crf', 22)
#number3
->addFileter(['-preset', 'ultrafast'], ['-crf', 22])
It still not working
please give me the example thanks

**Comment by pascalbaljet** [comment]
As I said before, please attach some meaningful information when you open an issue. There is no way I can help you without some debugging info and error logs. Maybe it's because you've spelled `addFilter` wrong?

Here is a test to show you how it works: https://github.com/pascalbaljetmedia/laravel-ffmpeg/blob/master/tests/AudioVideoTest.php#L143
