### ISSUE TITLE
Driver [] is not supported.

### ISSUE THREAD

**Issue by HeroSony** [pascalbaljetmedia/laravel-ffmpeg#39]
Hello mate!

help me please.
I've got this error.
`Driver [] is not supported.`

**Comment by pascalbaljet** [comment]
Please post your code so we can debug it.

**Comment by ahmed-h** [comment]
I just saw this same issue, and it seems that it is due to using the FFMpeg::fromDisk() function, because when I used fromFileSystem instead, I didn't see the error anymore (I did however get a different error because my implementation of fromFileSystem wasn't correct).

Still in the process of figuring this out, but I thought I'd shed some light on it.

I am using Laravel 5.5 and PHP 7.1 , Valet (running nginx) and installed everything through homebrew.

**Comment by pascalbaljet** [comment]
The ```fromDisk``` method works the same as Laravel's ```Storage::disk('local')```, you pass in the name of the disk you've configured in ```config/filesystems.php```.

The ```fromFilesystem``` method accepts an object that implements the [Filesystem contract](https://laravel.com/api/5.5/Illuminate/Contracts/Filesystem/Filesystem.html). A call to ```Storage::disk('local')``` actually gives you something that implements that contract.

**Comment by ahmed-h** [comment]
Thank you Pascal that solved it for me.

My code is: FFMpeg::fromDisk('public')->open('source-video/'. $filename);

This looks in my storage/app/public/source-video folder for my filename and opens it successfully for me to now chain further commands on it.

HeroSony I think you problem might be that you are not passing the right arguments in the fromDisk function. You can use 'local' for your root folder and 'public' for your public storage folder (if you have done php artisan storage:link)

**Comment by HeroSony** [comment]
Thank both of you. Anyway @ahmed-h I'll try it.

**Comment by HeroSony** [comment]
Great! Now error has gone. Thank all of you again.
